config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  resources :orders do
    resources :bids
    resource :closure do
      get 'addresses', to: 'closures#new_address'
      post 'addresses', to: 'closures#create_address'
    end
  end

end

app/models/bid.rb
class Bid < ApplicationRecord

  belongs_to :order
  belongs_to :user
  has_one :closure

  with_options presence: true do
    validates :message
    validates :delivery_time_remark
    validates :size_remark
    validates :material_remark
    validates :detail_remark
    validates :price_remark
  end

  validates :offer_price, allow_blank: true, numericality: { only_integer: true, message:"に半角数字が使用されていません" }

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :bid_info, only: [:show]

  def new
    @bid = Bid.new
    @order = Order.find(params[:order_id])
  end

  def create
    @bid = Bid.new(bid_params)
    if @bid.valid?
      @bid.save
      redirect_to root_path
    else
      @order = Order.find(params[:order_id])
      render :new
    end
  end

  def show
    @order = Order.find(params[:order_id])
  end

private

  def bid_params
    @order = Order.find(params[:order_id])
    params.require(:bid).permit(:offer_price, :price_ok, :size_ok, :material_ok, 
                                :detail_ok, :delivery_ok,
                                :price_remark, :size_remark, :material_remark,
                                :detail_remark, 
                                :delivery_time_remark, :message, 
                                :order_id).merge(user_id: current_user.id, order_id: @order.id)
  end

  def bid_info
    @bid = Bid.find(params[:id])
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/new.html.erb
<%= image_tag('crop2.png', class:'grain-pattern') %>
<%= render "shared/header" %>

<div class="order-screen">
  <h2 class="icon--name">
    <%= @order.name %>
  </h2>
  
　<div class="orders-main">
  <h2>自分でDIYできる条件を入力</h2>
  <%= form_with model: @bid, url: order_bids_path, local: true do |f| %>
  <%= render partial: 'shared/error_messages', locals: { model: f.object } %>

  <div>
    <table width="100%" height="300">
      <tbody>
        <tr>
          <th class="title-box">ジャンル</th>
          <td class="content-box"><%= image_tag "#{@order.type_id}.png", :size => '40x40' %></td>
        </tr>
        <tr>
          <th class="title-box">DIYクライアント</th>
          <td class="content-box"><%= @order.user.nickname %></td>
        </tr>
        <tr>
          <th class="title-box">発注経緯</th>
          <td class="content-box"><%= @order.story %></td>
        </tr>
        <tr>
          <th class="title-box">タイプ</th>
          <td class="content-box"><%= @order.type.name %></td>
        </tr>
      </tbody>
    </table>

    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">サイズ</th>
          <td class="content-box"><%= @order.size %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
          <%= f.radio_button :size_ok, :true, checked: true, class:"remove-input-mark" %>
          <%= f.label :size_ok_true, "承知しました！", class:"label-motion" %>
          
          <%= f.radio_button :size_ok, :false, class:"remove-input-mark" %>
          <%= f.label :size_ok_false, "ご提案があります！", class:"label-motion" %>
        </div>
        <div class="suggestion">サイズへの返信
          <span class="indispensable">必須</span>
          <%= f.text_area :size_remark, class:"suggestion", placeholder:"(100文字まで) 例)テーブルの天板をカットせずにそのままのサイズを使用すれば希望価格に近い金額になるかと思います。", maxlength:"100" %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">材質・塗装</th>
          <td class="content-box"><%= @order.material %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
          <%= f.radio_button :material_ok, :true, checked: true, class:"remove-input-mark" %>
          <%= f.label :material_ok_true, "承知しました！", class:"label-motion" %>
          
          <%= f.radio_button :material_ok, :false, class:"remove-input-mark" %>
          <%= f.label :material_ok_false, "ご提案があります！", class:"label-motion" %>
        </div>
        <div class="suggestion">材質への返信
          <span class="indispensable">必須</span>
          <%= f.text_area :material_remark, class:"suggestion", placeholder:"(100文字まで) 例)天板は鉄、その他はパイン材を使用します。", maxlength:"100" %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">詳細</th>
          <td class="content-box"><%= @order.detail %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
          <%= f.radio_button :detail_ok, :true, checked: true, class:"remove-input-mark" %>
          <%= f.label :detail_ok_true, "承知しました！", class:"label-motion" %>
          
          <%= f.radio_button :detail_ok, :false, class:"remove-input-mark" %>
          <%= f.label :detail_ok_false, "ご提案があります！", class:"label-motion" %>
        </div>
        <div class="suggestion">詳細への返信
          <span class="indispensable">必須</span>
          <%= f.text_area :detail_remark, class:"suggestion", placeholder:"(100文字まで) 例)詳細承知しました！細かいところこちらでいい感じに進めます。", maxlength:"100" %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作びの目安</th>
          <td class="content-box"><%= @order.delivery_time.name %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
          <%= f.radio_button :delivery_ok, :true, checked: true, class:"remove-input-mark" %>
          <%= f.label :delivery_ok_true, "承知しました！", class:"label-motion" %>
          
          <%= f.radio_button :delivery_ok, :false, class:"remove-input-mark" %>
          <%= f.label :delivery_ok_false, "ご提案があります！", class:"label-motion" %>
        </div>
        <div class="suggestion">制作日数への返信
          <span class="indispensable">必須</span>
          <%= f.text_area :delivery_time_remark, class:"suggestion", placeholder:"(100文字まで) 例)制作までに3週間程度いただければと思います。", maxlength:"100" %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作価格（送料込み）</th>
          <td class="content-box"><%= @order.price.to_s(:delimited) %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
          <%= f.radio_button :price_ok, :true, checked: true, class:"remove-input-mark" %>
          <%= f.label :price_ok_true, "承知しました！", class:"label-motion" %>
          
          <%= f.radio_button :price_ok, :false , class:"remove-input-mark" %>
          <%= f.label :price_ok_false, "ご提案があります！", class:"label-motion" %>
        </div>
        <div class="suggestion">
          <span class="optional">任意</span>
          オファー価格：<br>
          <%= f.text_field :offer_price, class:"offer-price-input", placeholder:"例）15,000" %> 円<br>
          価格への返信
          <span class="indispensable">必須</span>
          <%= f.text_area :price_remark, class:"suggestion", placeholder:"(100文字まで) 例)材料費だけで1万円近くになってしまいますので、上記の価格でいかがでしょうか？", maxlength:"100" %>
        </div>
      </div>
      <div class="message-area">
        <span class="indispensable">必須</span><br>クライアント様へメッセージ
        <%= f.text_area :message, class:"message-box", placeholder:"(100文字まで) 例)頑張りますので承諾いただけると嬉しいです。", maxlength:"100" %>
      </div>
      
      <div>
        <%= f.submit "上記の条件で入札します", class:"bid-btn" %>
      </div>
  </div>
  <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/bids/show.html.erb
<%= image_tag('crop2.png', class:'grain-pattern') %>
<%= render "shared/header" %>


<div class="order-screen">
  <h2 class="icon--name">
    <%= @order.name %>
  </h2>


  <div class="orders-main">
    <table width="100%" height="300">
      <tbody>
        <tr>
          <th class="title-box">ジャンル</th>
          <td class="content-box"><%= image_tag "#{@order.type_id}.png", :size => '40x40' %></td>
        </tr>
        <tr>
          <th class="title-box">DIYクライアント</th>
          <td class="content-box"><%= @order.user.nickname %></td>
        </tr>
        <tr>
          <th class="title-box">発注経緯</th>
          <td class="content-box"><%= @order.story %></td>
        </tr>
        <tr>
          <th class="title-box">タイプ</th>
          <td class="content-box"><%= @order.type.name %></td>
        </tr>
      </tbody>
    </table>

    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">サイズ</th>
          <td class="content-box"><%= @order.size %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.size_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.size_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">材質・塗装</th>
          <td class="content-box"><%= @order.material %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.material_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.material_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">詳細</th>
          <td class="content-box"><%= @order.detail %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.detail_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.detail_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作びの目安</th>
          <td class="content-box"><%= @order.delivery_time.name %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.delivery_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.delivery_time_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作価格（送料込み）</th>
          <td class="content-box"><%= @order.price.to_s(:delimited) %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.price_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div>
          オファー価格：<br>
          <div class="offer-price-display">
          <% if @bid.offer_price %>
            <%= @bid.offer_price.to_s(:delimited) %> 円
          <% else %>
            無し
          <% end %>
          </div>
          <div class="reply-from-diyer">
            <%= @bid.price_remark %>
          </div>
        </div>
      </div>
      <div class="message-title"><span class="message-title2">DIY製作者様からメッセージ</span></div>
      <div class="message-from-diyer">
        <%= @bid.message %>
      </div>
  </div>
</div>

<div class="closure-wrapper">
  <h2 class="agree-sentence">下の同意ボタンを押すとDIYされます</h2><br>
  <span class="indispensable">メッセージ必須</span>
  <%= form_with model: @closure, url: order_closure_path, local: true do |f| %>
    <div>
      <%= f.text_area :reply, class:"closure-long-reply", placeholder:"(500文字まで) 例)よろしくお願いします", rows:"5",maxlength:"500" %>
    </div>
      <%= f.hidden_field :bid_id, value: @bid.id %>
    <div class="closure-btn-cotents">
      <%= f.submit "以上の条件で同意します", class:"closure-btn" %>
    </div>
  <% end %>
</div>

<%= render "shared/footer" %>