config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  resources :orders do
    resources :bids
    resource :closure do
      get 'addresses', to: 'closures#new_address'
      post 'addresses', to: 'closures#create_address'
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :type
  belongs_to_active_hash :delivery_time
  belongs_to :user
  has_many :bids
  has_one :closure

  with_options presence: true do
    validates :name
    validates :story
    validates :size
    validates :price, numericality: { only_integer: true,
                                      greater_than: 299, less_than: 300001 }
  end

    validates :type_id, numericality: { other_than: 1, message: "が選択されていません" }
    validates :delivery_time_id, numericality: { other_than: 1, message: "が選択されていません" }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_order, only: [:show, :edit]

  def index
    @orders = Order.all.order(id: "DESC").limit(6)
    @bids = Bid.all
    @closures = Closure.all
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      @order.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @closures = Closure.all
  end

  def edit
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    order = Order.find(params[:id])
    if order.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :story, 
                                  :type_id, :price, 
                                  :size, :material, :detail, 
                                  :delivery_time_id).merge(user_id: current_user.id)
  end

  def set_order
    @order = Order.find(params[:id])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="order-contents">
  <header class="order-header">
    <%= image_tag('crop2.png', class:'grain-pattern') %>
      <div class="top-content">
        <%= link_to image_tag("top.png"), "/" %>
      </div>
  </header>
  <div class="orders-main">
    <h2>オーダー家具の情報を編集できます</h2>
    <%= form_with(model: @order, local: true) do |f| %>

    <%= render partial: 'shared/error_messages', locals: { model: f.object } %>

    <div>
      <div class="weight-bold-text">
        家具アイコン
        <span class="indispensable">必須</span>
      </div>
      <div class="choose-icon">
        <p>
          クリックして家具のタイプ選択
        </p>
        <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"select-box", id:"icon-type"}) %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        家具の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"order-short", placeholder:"(20文字まで) 例)ハイテーブル", maxlength:"20" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          家具の発注目的
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :story, class:"order-long", placeholder:"(500文字まで）例）赤ちゃんが大きくなり普通のテーブル高さですと物を落としてしまいます。室内で使用する手の届かないくらいのハイテーブルがほしいと思いました。" ,rows:"4" ,maxlength:"500" %>
      </div>
      <div class="weight-bold-text">
        家具のサイズ
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :size, class:"order-medium", placeholder:"（200文字まで) 例)カウンターテーブルと合わせたいので、おおよそ高さ100x幅180x奥行き50cmでお願いします。幅はぴったりの寸法がいいです。", rows:"3",maxlength:"200" %>
      <div class="weight-bold-text">
        家具の材質
        <span class="optional">任意</span>
      </div>
      <%= f.text_area :material, class:"order-medium", placeholder:"(200文字まで) 例)テーブル自体は木製であれば種類は気にしません。表面はアメ色のペンキを塗ってほしいです", rows:"3",maxlength:"200" %>
      <div class="weight-bold-text">
        家具のその他希望
        <span class="optional">任意</span>
      </div>
      <%= f.text_area :detail, class:"order-long", placeholder:"(500文字まで) 例)階段から搬入して２階で使おうと思っています。天板と脚部分は分離した状態で送ってきてほしいです。天板と脚をビスで止めれば組み立てられるようにしてください。", rows:"3",maxlength:"500" %>
    </div>
    <div class="items-detail">
        <div class="weight-bold-text">
          制作希望日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_time_id, DeliveryTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
        <div class="price-content">
          <div class="price-text">
            <span>支払い価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span>¥</span>
          <%= f.text_field :price, class:"price-input", placeholder:"例）20,000" %>
        </div>
    <div class="order-btn-contents">
      <%= f.submit "オーダーを編集" ,class:"order-btn" %>
      <%=link_to 'Topへ', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/orders/index.html.erb
<%= image_tag('crop2.png', class:'grain-pattern') %>
<header class='top-page-header'>
  <div class='top-contents'>
    <%= link_to image_tag("top.png", class:"top-icon"), "/" %>
  </div>
  <div class="top-header-position">
    <ul class='lists'>
      <%# ログインの有無で表示が分岐%>
      <% if user_signed_in? %>
        <li><%= link_to "#{current_user.nickname} さんのマイページ", '#', class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>

  <% if user_signed_in? %>
    <ul>
      <% @bids.each do |bid|%>
        <% if current_user.id == bid.order.user_id %>
          <% unless @closures.exists?(order_id: bid.order_id)%>
          <li>
            <%= link_to image_tag("19.png", width: '30'), order_bid_path(bid.order_id, bid.id)%>
            <%= "#{bid.user.nickname}さんに入札されています。プレゼントマークをクリック！" %>
          </li>
          <% else %>
            <div>
              <%= "' #{bid.order.name} 'はクローズされました" %>
            </div>
          <% end %>
        <% elsif @closures.exists?(bid_id: bid.id) && current_user.id == bid.user_id %>
          <div>
            <%= link_to "あなたの入札で'#{bid.order.name}'がクローズされました！詳細を確認してみましょう！", order_closure_path(bid.order_id, bid.id) %>
          </div>
        <% end %>
      <% end %>
    </ul>
  <% end %>
  </div>
</header>

<div class="wrapper">
    <%= link_to(new_order_path, class:'remove-under-line') do %>
      <div class="order-side">
        <div class="order-desc">DIY家具屋さんを使うと、<br>どこかの誰かがあなたの家具を作ってくれます。<br>オーダーするために画像をクリックしてください。</div>
      </div>
    <% end %>
</div>
<%# オーダー一覧表示部分 %>
<div>
  <h2 class="furniture-index-list">DIYできる家具一覧</h2>
  <h3 class="furniture-index-select">あなたがDIYしたい家具を下から選んでください。</h3>
  <ul class='orders-list'>
    <% @orders.each do |order| %>
      <li class='order-alone'>
        <%= link_to order_path(order.id), class:"remove-underline" do %>
          <div class="image-content">
            <%= image_tag "#{order.type_id}.png", class:"icon-size" %>

            <% if @closures.exists?(order_id: order.id) %>
              <div class='closed'>
                <span>Colsed</span>
              </div>
            <% end %>   

          </div>
          <div class="individual-name">
            <%= order.name %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>

<%= render "shared/footer" %>

app/views/orders/new.html.erb
<div class="order-contents">
  <header class="order-header">
    <%= image_tag('crop2.png', class:'grain-pattern') %>
      <div class="top-content">
        <%= link_to image_tag("top.png"), "/" %>
      </div>
  </header>
  <div class="orders-main">
    <h2>オーダー家具の情報を入力</h2>
    <%= form_with(model: @order, local: true) do |f| %>

    <%= render partial: 'shared/error_messages', locals: { model: f.object } %>

    <div>
      <div class="weight-bold-text">
        家具アイコン
        <span class="indispensable">必須</span>
      </div>
      <div class="choose-icon">
        <p>
          クリックして家具のタイプ選択
        </p>
        <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"select-box", id:"icon-type"}) %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        家具の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"order-short", placeholder:"(20文字まで) 例)ハイテーブル", maxlength:"20" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          家具の発注目的
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :story, class:"order-long", placeholder:"(500文字まで）例）赤ちゃんが大きくなり普通のテーブル高さですと物を落としてしまいます。室内で使用する手の届かないくらいのハイテーブルがほしいと思いました。" ,rows:"4" ,maxlength:"500" %>
      </div>
      <div class="weight-bold-text">
        家具のサイズ
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :size, class:"order-medium", placeholder:"（200文字まで) 例)カウンターテーブルと合わせたいので、おおよそ高さ100x幅180x奥行き50cmでお願いします。幅はぴったりの寸法がいいです。", rows:"3",maxlength:"200" %>
      <div class="weight-bold-text">
        家具の材質
        <span class="optional">任意</span>
      </div>
      <%= f.text_area :material, class:"order-medium", placeholder:"(200文字まで) 例)テーブル自体は木製であれば種類は気にしません。表面はアメ色のペンキを塗ってほしいです", rows:"3",maxlength:"200" %>
      <div class="weight-bold-text">
        家具のその他希望
        <span class="optional">任意</span>
      </div>
      <%= f.text_area :detail, class:"order-long", placeholder:"(500文字まで) 例)階段から搬入して２階で使おうと思っています。天板と脚部分は分離した状態で送ってきてほしいです。天板と脚をビスで止めれば組み立てられるようにしてください。", rows:"3",maxlength:"500" %>
    </div>
    <div class="items-detail">
        <div class="weight-bold-text">
          制作希望日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_time_id, DeliveryTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
        <div class="price-content">
          <div class="price-text">
            <span>支払い価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span>¥</span>
          <%= f.text_field :price, class:"price-input", placeholder:"例）20,000" %>
        </div>
    <div class="order-btn-contents">
      <%= f.submit "オーダー", data: { confirm: "家具をオーダーしてもよろしいですか？" }, class:"order-btn" %>
    </div>
    <div class="back-btn-contents">
      <%=link_to 'Topへ', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/orders/show.html.erb
<%= render "shared/header" %>

<%# オーダーの概要 %>
<div>
  <div class="order-screen">
    <h2 class="icon--name">
      <%= @order.name %>
    </h2>

    <table>
      <tbody>
        <tr>
          <th class="title-box">ジャンル</th>
          <td class="content-box"><%= image_tag "#{@order.type_id}.png", :size => '40x40' %></td>
        </tr>
        <tr>
          <th class="title-box">発注経緯</th>
          <td class="content-box"><%= @order.story %></td>
        </tr>
        <tr>
          <th class="title-box">DIYクライアント</th>
          <td class="content-box"><%= @order.user.nickname %></td>
        </tr>
        <tr>
          <th class="title-box">タイプ</th>
          <td class="content-box"><%= @order.type.name %></td>
        </tr>
        <tr>
          <th class="title-box">サイズ</th>
          <td class="content-box"><%= @order.size %></td>
        </tr>
        <tr>
          <th class="title-box">材質・塗装</th>
          <td class="content-box"><%= @order.material %></td>
        </tr>
        <tr>
          <th class="title-box">詳細</th>
          <td class="content-box"><%= @order.detail %></td>
        </tr>
        <tr>
          <th class="title-box">希望制作びの目安</th>
          <td class="content-box"><%= @order.delivery_time.name %></td>
        </tr>
      </tbody>
    </table>

    <div class="order--price">
      <span>
        <%= @order.price.to_s(:delimited) %>円
      </span>
    </div>

    <% unless @closures.exists?(order_id: @order.id) %>
      <% if user_signed_in? && current_user.id == @order.user_id %>
      <div class="edit-destroy-btn-wrapper">
        <div class="edit-destroy-btn"><%= link_to 'オーダーの編集', edit_order_path(@order.id), method: :get,id:"confirm-destroy", class: "order-pink-btn" %></div>
        <div class="edit-destroy-btn"><%= link_to '削除', order_path(@order.id), method: :delete, class:'order-destroy', data: { confirm: '削除してもよろしいですか？' } %></div>
      </div>
      <% else %>
        <% unless user_signed_in? && @order.bids.exists?(user_id: current_user.id) %>
          <div>
            <%= link_to '入札画面に進む', new_order_bid_path(@order.id), class:"to-bid-btn" %>
          </div>
        <% else %>
          <div><span class="bid-already">あなたはこの家具をすでに入札しています</span></div>
        <% end %>
      <% end %>
    <% else %>
      <div>
        <span class="bid-already">この家具はすでに入札されています</span>
      </div>
    <% end %>

    <div class="show-back-btn-contents">
      <%=link_to 'Topへ', root_path, class:"show-back-btn" %>
    </div>
  
  </div>
</div>

<%= render "shared/footer" %>