config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  resources :orders do
    resources :bids
    resource :closure do
      get 'addresses', to: 'closures#new_address'
      post 'addresses', to: 'closures#create_address'
    end
  end

end

app/models/closure.rb
class Closure < ApplicationRecord

  belongs_to :bid
  belongs_to :order
  has_one :address

  validates :reply, presence: true
end

app/controllers/closures_controller.rb
class ClosuresController < ApplicationController

  def create
    @closure = Closure.new(closure_params)
    unless @closure.valid?
      redirect_to root_path and return
    end
    
    session["closure_data"] = @closure.attributes
    @address = @closure.build_address
    render :new_address

  end

  def create_address
    @closure = Closure.new(session["closure_data"])
    @address = Address.new(address_params)
     unless @address.valid?
       render :new_address and return
     end
    
    @closure.build_address(@address.attributes)
    if @closure.save
      @address[:closure_id] = @closure.id
      @address.save
    end
    session["closure_data"].clear
    pay_item
    render :create_address
  end

  def show
    @order = Order.find(params[:order_id])
    @closure = Closure.find_by(order_id: @order.id)
    @bid = Bid.find(params[:format])
  end

  private

  def closure_params
    params.permit(:reply, :order_id, :bid_id)
  end

  def address_params
    params.require(:address).permit(:name, :postal_code, :prefecture_id, 
                                    :location, :building, :phone).merge(token: params[:token])
  end

  def pay_item
    @order = Order.find(params[:order_id])
    @bid = Bid.find_by(order_id: @order.id)

    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if @bid.offer_price
      Payjp::Charge.create(
        amount: @bid.offer_price,
        card: address_params[:token],
        currency: 'jpy'
      )
    else
      Payjp::Charge.create(
        amount: @order.price,
        card: address_params[:token],
        currency: 'jpy'
      )
    end
  end

end

app/helpers/closures_helper.rb
module ClosuresHelper
end

app/views/closures/create_address.html.erb
<h2>住所入力、お支払いが完了しました</h2>
<%= link_to "トップへ戻る", root_path%>

app/views/closures/new_address.html.erb
<%= image_tag('crop2.png', class:'grain-pattern') %>
<%= render "shared/header" %>

<h2>住所情報登録</h2>

<%= form_with model: @address, url: addresses_order_closure_path, id: 'charge-form', local: true do |f| %>

  <%= render partial: 'shared/error_messages', locals: { model: f.object } %>

  <div class="field">
    <%= f.label :name, value:"お届け先のお名前" %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :postal_code %><br/>
    <%= f.text_field :postal_code %>
  </div>

  <div class="field">都道府県<br>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
  </div>

  <div class="field">
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :building %><br/>
    <%= f.text_field :building %>
  </div>

  <div class="field">
    <%= f.label :phone %><br/>
    <%= f.text_field :phone %>
  </div>

    <h2>カード情報を入力してください</h2>
  <div class='form-wrap'>
    <%= f.label :number,  "カード番号" %>
    <%= f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>
  <div class='form-wrap'>
    <%= f.label :cvc ,"ＣＶＣ" %>
    <%= f.text_field :cvc, class:"cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
  </div>
  <div class='form-wrap'>
    <p>有効期限</p>
    <div class='input-expiration-date-wrap'>
      <%= f.text_field :exp_month, class:"exp_month", placeholder:"例)3" %>
      <p>月</p>
      <%= f.text_field :exp_year, class:"exp_year", placeholder:"例)24" %>
      <p>年</p>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "入力を完了する" %>
  </div>
<% end %>

app/views/closures/show.html.erb
<%= image_tag('crop2.png', class:'grain-pattern') %>
<%= render "shared/header" %>

<div class="visibiliry-hidden", id="hidden-time"><%= @closure.created_at %></div>
<div class="visibiliry-hidden", id="hidden-id"><%= @order.delivery_time.id %></div>
<div class="count-box">
  <p>家具制作終了日までの目安：</p>
  <div class="count-result", id="result"></div>
</div>
<script>
  var hiddenTime = document.getElementById('hidden-time');
  var startTime = new Date(hiddenTime.textContent);

  var hiddenId = document.getElementById('hidden-id');
  var Id = hiddenId.textContent;

  if(Id == 2){
    startTime.setDate(startTime.getDate() + 3);
  } else if(Id = 3){
    startTime.setDate(startTime.getDate() + 7);
  } else if(Id = 4){
    startTime.setDate(startTime.getDate() + 14);
  } else if(Id = 5){
    startTime.setMonth(startTime.getMonth() + 1);
  } else if(Id = 6){
    startTime.setDate(startTime.getDate() + 45);
  } else{
    startTime.setMonth(startTime.getMonth() + 2);
  }

  // 1秒おきにカウントダウン
  var id = setInterval(function(){
    var nowTime = new Date();
    var period = startTime - nowTime
    period--;
    
    if(period >= 0){
      var day = Math.floor(period / (1000 * 60 * 60 * 24));
      period -=  (day　*(1000 * 60 * 60 * 24));
      var hour = Math.floor(period / (1000 * 60 * 60));
      period -= (hour *(1000 * 60 * 60));
      var minutes =  Math.floor(period / (1000 * 60));
      period -= (minutes * (1000 * 60));
      var second = Math.floor(period / 1000);
      var insert = "";
      insert += '<span class="h">' + day +'日' + '</span>';
      insert += '<span class="h">' + hour + '時'+'</span>';
      insert += '<span class="m">' + minutes +'分' + '</span>';
      insert += '<span class="s">' + second + '秒'+ '</span>';
      document.getElementById('result').innerHTML = insert;
    } else{
      clearInterval(id);
      insert = "制作期間終了です！"
      document.getElementById('result').innerHTML = insert;
    }
  }, 1000);
</script>

<div>
  <div class="closed-text"><%= "#{@order.name}は以下の条件で入札されています" %></div>
      <div class="closed-contents"><依頼者さんからのメッセージ><br>
        <%= @closure.reply %>
      </div>
</div>

<div class="order-screen">
  <h2 class="icon--name">
    <%= @order.name %>
  </h2>


　<div class="orders-main">
    <table width="100%" height="300">
      <tbody>
        <tr>
          <th class="title-box">ジャンル</th>
          <td class="content-box"><%= image_tag "#{@order.type_id}.png", :size => '40x40' %></td>
        </tr>
        <tr>
          <th class="title-box">DIYクライアント</th>
          <td class="content-box"><%= @order.user.nickname %></td>
        </tr>
        <tr>
          <th class="title-box">発注経緯</th>
          <td class="content-box"><%= @order.story %></td>
        </tr>
        <tr>
          <th class="title-box">タイプ</th>
          <td class="content-box"><%= @order.type.name %></td>
        </tr>
      </tbody>
    </table>

    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">サイズ</th>
          <td class="content-box"><%= @order.size %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.size_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.size_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">材質・塗装</th>
          <td class="content-box"><%= @order.material %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.material_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.material_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">詳細</th>
          <td class="content-box"><%= @order.detail %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.detail_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.detail_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作びの目安</th>
          <td class="content-box"><%= @order.delivery_time.name %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.delivery_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div class="reply-from-diyer">
          <%= @bid.delivery_time_remark %>
        </div>
      </div>
    <table width="100%" height="100" class="gap">
      <tbody>
        <tr>
          <th class="title-box">希望制作価格（送料込み）</th>
          <td class="content-box"><%= @order.price.to_s(:delimited) %></td>
        </tr>
      </tbody>
    </table>
      <div>
        <div class="checkbox-position">
        <% if @bid.price_ok == true %>
          <div class="label-motion checked">承知しました！</div>
          <div class="label-motion">ご提案します！</div>
        <% else %>
          <div class="label-motion">承知しました！</div>
          <div class="label-motion checked">ご提案します！</div>
        <% end %>
        </div>
        <div>
          オファー価格：<br>
          <div class="offer-price-display">
          <% if @bid.offer_price %>
            <%= @bid.offer_price.to_s(:delimited) %> 円
          <% else %>
            無し
          <% end %>
          </div>
          <div class="reply-from-diyer">
            <%= @bid.price_remark %>
          </div>
        </div>
      </div>
      <div class="message-title"><span class="message-title2">依頼者さんに送ったメッセージ</span></div>
      <div class="message-from-diyer">
        <%= @bid.message %>
      </div>
  </div>
</div>

<%= render "shared/footer" %>